turn_on:
  name: "Activate"
  description: "Activates a scene with given filters."
  target:
    entity:
      domain: scene
  fields:
    entity_filter:
      name: "Entity Filter"
      description: "List of entity IDs to include. Only these entities will be affected by the scene activation."
      selector:
        entity:
          multiple: true
      example: |
        - light.tv_back_light
        - light.theatre
    area_filter:
      name: "Area Filter"
      description: "Name of the area to include. Only entities in this area will be affected by the scene activation."
      selector:
        area:
          multiple: true
      example: |
        - living_room
        - kitchen
    transition:
      name: "Transition"
      description: "Time it takes the devices to transition into the states defined in the scene."
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
