activate:
  name: Activate
  description: Activates a scene with given filters.
  target:
    entity:
      domain: scene
  fields:
    entity_filter:
      selector:
        entity:
          multiple: true
      example: |
        - light.tv_back_light
        - light.theatre
    area_filter:
      selector:
        area:
          multiple: true
      example: |
        - living_room
        - kitchen
    transition:
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
