name: Verification

on:
  push:

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Nix
        uses: jpaju/gh-commons/actions/setup-nix@main

      - name: Install dependencies
        run: nix develop --command uv sync --locked

      - name: Run unit tests
        run: nix develop --command uv run --locked pytest

  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master
